apiVersion: v1
kind: Pod
metadata:
  namespace: default
  labels:
    run: nginx-tester
  name: nginx-tester
spec:
  containers:
    - image: nginx
      name: nginx-tester
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
